config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "flights#index"
  resources :flights
  resources :passengers do
    collection do
      get 'passenger_dtl' 
    end
  end
    resources :ticket_details
  resources :searches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user.can :read, Flight
    return if user.guest?
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :flights
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :airport
    has_many :ticket_detail
    has_many :passenger, through: :ticket_detail

    
    def self.search(search)
        if search
            where(["departure_code LIKE ?", "%#{search}%"])
           
        else
            all
        end
    end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    has_many :ticket_detail
    has_many :flight, through: :ticket_detail
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/ticket_detail.rb
class TicketDetail < ApplicationRecord
    belongs_to :flight
    belongs_to :passenger

    validates :status, acceptance: { accept: ['Booked', 'Cancel'] }
    # enum status: [:Booked,:Cancel]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user,:admin]
  after_initialize :set_default_role, :if =>:new_record?
  def  set_default_role
    self.role ||= :user    
  end
  def guest?
    persisted?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.search(params[:search])
    
    
  end
  def new
    if current_user.admin?
      @flight = Flight.new
      @airport_ids = Airport.ids
    else
      redirect_to('/')
    end
  end

  def create
     @flight = Flight.new(flight_params)

     if @flight.save
        redirect_to @flight
     else
        render :new, status: :unprocessable_entity
     end
  end




  private 
    def flight_params
      params.require(:flight).permit(:departure_code,:arrival_code,:available_seats,:total_seats,:duration,:start_date,:airport_id)

    end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
    def new 
        @fid = params[:f_id]
        @passenger = Passenger.new
    end
    
    def create
        @passenger = Passenger.create(passenger_params)
        
        if @passenger.save
            @flight_id = params[:f_id]
            redirect_to("/ticket_details/new?pass_id=#{@passenger.id}&f_id=#{@flight_id}")
        end
    end
    def passenger_dtl
        if current_user.admin?
            flight = Flight.find(params[:f_id]) 
            passengers_ids = flight.ticket_detail.where(status: "Booked").pluck(:passenger_id)
            @passengers = Passenger.find(passengers_ids)
        else
            redirect_to('/')
        end    
    end

        private

        def passenger_params
            params.require(:passenger).permit(:first_name,:last_name,:email,:phone_number,:address)
        end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def new
        @search = Search.new
    end

    def create
        @search = Search.create(search_params)
        redirect_to @search
    end

    def show
        @search = Search.find([params[:id]])
    end

    private
        def search_params
            params.require(:search).permit(:departure_code,:arrival_code, :start_date, :passenger)
        end    
end
    

app/controllers/ticket_details_controller.rb
class TicketDetailsController < ApplicationController
  def new

    @ticket_detail = TicketDetail.new 
    
  end
  def create
    @ticket_detail = TicketDetail.new(ticket_params)
    if @ticket_detail.save
      redirect_to('/')
    end
  end
private
  def ticket_params
    params.require(:ticket_detail).permit(:flight_id,:passenger_id,:status)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/ticket_details_helper.rb
module TicketDetailsHelper
end

app/views/flights/_form.html.erb
<%= form_with model: flight do |form| %>
    <div>
        <%= form.label :departure_code %><br>
        <%= form.text_field :departure_code %><br>
        <% flight.errors.full_messages_for(:departure_code).each do  |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :arrival_code %><br>
        <%= form.text_field :arrival_code %><br>
        <% flight.errors.full_messages_for(:arrival_code).each do  |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :total_seats %><br>
        <%= form.text_field :total_seats %><br>
        <% flight.errors.full_messages_for(:total_seats).each do  |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :available_seats %><br>
        <%= form.text_field :available_seats %><br>
        <% flight.errors.full_messages_for(:available_seats).each do  |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :duration %><br>
        <%= form.text_field :duration %><br>
        <% flight.errors.full_messages_for(:duration).each do  |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :airport_id %><br>
        <%= form.select :airport_id , options_for_select(airport_id) %><br>
    </div>

<br>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/flights/_search_flight_form.html.erb
<%#= form_tag(search_path, :method => "get") do  %>

    <%#=search_field_tag :search, params[:search], placeholder: "Type", %>
        <div>
            <%#= button_tag "Search for Flights" %>
        </div>    
    
    
    
    
    
    <%#= form.label :departure_code, "From:" %>
        <%#= form.select :departure_code, [["Pakistan", "pak"], ["India", "ind"], ["China", "chin"]], selected: "pak" %><br>
        
        <%#= form.label :arrival_code, "To:" %>
        <%#= form.select :arrival_code, [["Pakistan", "pak"], ["India", "ind"], ["China", "chin"]], selected: "ind" %><br>
       
        
        <%#= form.label :num_of_passenger, "Number of Passenger:" %>
        <%#= form.select :num_of_passenger, [1,2,3,4] %><br>
        
        <%#= form.label :num_of, "Number of Passenger:" %>
        <%#= form.date_field :start_time %>
        
        <%#= form.submit "Search" %>
<%# end %>
        

app/views/flights/index.html.erb
<div class="container ">
<h1>Wellcom, <%= current_user.email %></h1>
<h2>Your role is [<%= current_user.role %>]</h2>
<div class="row mt-4">
  <div class="col text-center  text-light">
  <div class="card bg-dark text-white " >
  <%= image_tag 'flighttextless.jpg',alt: 'icon' %>
  <div class="card-img-overlay  d-flex justify-content-center flex-column">
  <div class="bg-dark p-5">  
  <% if current_user.admin?%> 
    <h1 class="card-title  text-light"><%= link_to "Create New Flights", new_flight_path , class: "btn btn-primary"%></h1>
  
    <% else %>
    <h1 class="card-title  text-light">Book Your flights</h1>

  <% end %>

    <p class="card-text ">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text">Last updated 3 mins ago</p>
    </div>
  </div>
</div>
  <h1></h1>
  </div>

  <div class="">
        <h3 class="mt-5">Searching flights by Departure Airport</h3>
        <%= form_tag flights_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", class:"btn btn-primary" %>
        <% end %>
  </div>
<br><br>

<table class="table table-hover mt-5 ">
<thead>
        <tr>
        <th>Departure Airport</th>
            <th>Arrival Airport</th>
            <th>Duration</th>
            <th>Booked</th>
            <% if current_user.admin? %>
            <th>Passengers Detail</th>
            <% end %>
            <th>Ticket Booking</th>



            

            
            </tr>
            </thead>
    <tbody>
    <% @flights.each do |f| %>
        <tr>
            <td><%= f.departure_code %></td>
            <td><%= f.arrival_code %></td>
            <td><%= f.duration %></td>
            <td><%= f.ticket_detail.where(status: "Booked").count %></td>
            <% if current_user.admin? %>
            <td><%= link_to "Passengers Details", passenger_dtl_passengers_path(f_id: f.id)%></td>
            <% end %>
            <td><%= link_to "Booking", new_passenger_path(f_id: f.id)%></td>
            
            </tr>
            <% end %>
            </tbody>
            </table>
            </div>
            </div>
            
            
            
            
            <%#= link_to "Advance Search", new_search_path %><br><br><br>
            <%#= f.ticket_detail.where.not(status: "Booked").count %>

app/views/flights/new.html.erb
<h1>Create Flights</h1>
<%= render "form" ,flight: @flight, airport_id: @airport_ids %>

app/views/flights/search.html.erb
<h1>Search Flights</h1>

<%= render "search_flight_form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketBooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">
      <ul class="navbar-nav ">
      <% if user_signed_in? %>
        <li class="nav-item ">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:'nav-link'%>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Register", new_user_registration_path, class: 'nav-link' %>

        </li>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: 'nav-link' %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>

  </div>
  </body>
</html>

app/views/passengers/_form.html.erb
<div class="container">
<%= form_with model: passenger do |form| %>
    <div>
        <%= form.label :first_name %><br>
        <%= form.text_field :first_name %><br>
        <% passenger.errors.full_messages_for(:first_name).each do  |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
      <%= hidden_field_tag('f_id',params[:f_id]) %>
    </div>
    <div>
        <%= form.label :last_name %><br>
        <%= form.text_field :last_name %><br>
        <% passenger.errors.full_messages_for(:last_name).each do  |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :email %><br>
        <%= form.text_field :email %><br>
        <% passenger.errors.full_messages_for(:email).each do  |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :phone_number %><br>
        <%= form.text_field :phone_number %><br>
        <% passenger.errors.full_messages_for(:phone_number).each do  |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :address %><br>
        <%= form.text_field :address %><br>
        <% passenger.errors.full_messages_for(:address).each do  |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
<br>

    <div>
        <%= form.submit "Create Passenger" , class:"btn btn-success mt-2" %>
    </div>
<% end %>

</div>

app/views/passengers/new.html.erb
<h1>Enter Passenger Detail</h1>

<%= render "form", passenger: @passenger %>

app/views/passengers/passenger_dtl.html.erb
<div class="container">
<div class="row">
    <div class="col mt-5"><h1 class="text-center">Passengers Detail</h1></div>
</div>

<table class="table table-dark table-hover mt-5">
<thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Address</th>
         

            
        </tr>
    </thead>
    <tbody>
        <% @passengers.each  do |p| %>
            <tr>
                <td><%= p.first_name %></td>
                <td><%= p.last_name %></td>
                <td><%= p.email %></td>
                <td><%= p.phone_number %></td>
                <td><%= p.address %></td>

            </tr>
        <% end %>
    </tbody>
</table>
</div>

app/views/searches/new.html.erb
<h1> Advance Search</h1>
<%= form_for model: @search,  do |s| %>
    <div>
        <%= s.label :departure_code %>
        <%= s.text_field :departure_code %>
    </div>

    <div>
        <%= s.label :arrival_code %>
        <%= s.text_field :arrival_code %>
    </div>
    <div>
        <%= s.label :start_date %>
        <%= s.text_field :start_date %>
    </div>

    <div>
        <%= s.label :passenger %>
        <%= s.text_field :passenger %>
    </div>
<% end %>

app/views/ticket_details/_form.html.erb
<%= form_with model: ticket_detail do |form| %>

    <div>
        <%= form.label :status %><br>
        <%= form.select :status , ["Booked","Cancel"] %><br>
    </div>
    <div>
        <%= form.label :passenger_id %><br>
        <%= form.number_field :passenger_id, value: params[:pass_id] %>
    </div>

    <div>
        <%= form.label :flight_id %><br>
        <%= form.number_field :flight_id, value: params[:f_id].to_i %>
    </div>

<br>

    <div>
        <%= form.submit :Generate_Ticket%>
    </div>
<% end %>

app/views/ticket_details/new.html.erb
<h1>Booking Ticket Here</h1>

<%= render "form", ticket_detail: @ticket_detail %>